apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pfvk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pfvk
    app.kubernetes.io/part-of: cin4s-839-0037-app
  name: devfile-sample-pfvk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pfvk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pfvk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0037-tenant/cin4s-839-0037-app/devfile-sample-pfvk@sha256:806949cdb9704081c2c9b64582a556c4cefde2aecb317a74f510869d22149dc5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
