apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pfvk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0037-tenant/cin4s-839-0037-app/devfile-sample-pfvk@sha256:806949cdb9704081c2c9b64582a556c4cefde2aecb317a74f510869d22149dc5
        name: my-nodejs
        resources: {}
status: {}
